### ISSUE TITLE
WARNING: high error rate, more details with --display-optimizer-choice？

### ISSUE THREAD

**Issue by maxwellgodv** [zama-ai/concrete-ml#95]
<img width="394" alt="1bbbb1843a4ed7bd4278b72ad17807e" src="https://github.com/zama-ai/concrete-ml/assets/127387074/24479ef2-6552-407a-89d8-93eaffe98e5c">
Hello ，What does this mean？

**Comment by RomanBredehoft** [comment]
Hello, 
Would you be able to give us more info about your issue ? More precisely, would it be possible to : 
- indicate to us which model you are working with 
- set `verbose=True` when compiling your model (depending what you are doing: `compile`, `compile_torch_model`, etc.) and share us the printed details 

Many thanks !

**Comment by maxwellgodv** [comment]
[https://github.com/zama-ai/concrete-ml/blob/release/1.1.x/use_case_examples/cifar_brevitas_finetuning/CifarInFhe.ipynb](url)
After updating the new version of concrete ml, this issue occurred. In previous versions, there was no such warning

**Comment by RomanBredehoft** [comment]
Thanks for reporting ! We are indeed getting the same warning and are thus currently investigating on what could be the issue :slightly_smiling_face:

**Comment by kcelia** [comment]
Hello, 
Thanks for reporting the warning! 
We have fixed the issue on our end, but in the meantime, you can also make a fix on your side to continue.

```
def fhe_compatibility(model: Callable, data: DataLoader) -> Callable:
    qmodel = compile_brevitas_qat_model(
        model.to("cpu"),
        # Training
        torch_inputset=data,
        show_mlir=False,
        output_onnx_file="test.onnx",
    )
    return qmodel
```
Thanks !

**Comment by maxwellgodv** [comment]
Hello, thank you for replying to me.
But I still have a problem.
Do you mean that the configuration and p_error parameters are not required？
Can you explain these two parameters to me？

**Comment by andrei-stoian-zama** [comment]
Hi, you can find an explanation of `p_error` in [this documentation page](https://docs.zama.ai/concrete-ml/advanced-topics/advanced_features). Here the solution proposed is to remove the custom `p_error` value that this example was setting. 

You mention that you still have a problem, can you please elaborate ?

**Comment by maxwellgodv** [comment]
Thanks，How fhe_simulation_inference function simulate Homomorphic encryption?Where can I see the  details of  simulation?

**Comment by umut-sahin** [comment]
In Concrete v1, homomorphic encryption wasn't simulated, computation graph was walked and evaluated (and some errors are added before TLUs to kinda simulate p_error). Here are the relevant pieces of code:
- https://github.com/zama-ai/concrete/blob/cb19989fe15970ef6d993e75c3a512f07c0a5408/frontends/concrete-python/concrete/fhe/compilation/circuit.py#L59-L72
- https://github.com/zama-ai/concrete/blob/cb19989fe15970ef6d993e75c3a512f07c0a5408/frontends/concrete-python/concrete/fhe/representation/graph.py#L53-L66
- https://github.com/zama-ai/concrete/blob/cb19989fe15970ef6d993e75c3a512f07c0a5408/frontends/concrete-python/concrete/fhe/representation/graph.py#L68-L188

With Concrete v2, homomorphic encryption is simulated! We've introduced a new backend to do that and new simulation is using the same compiler architecture, so it's much more accurate. Here is the relevant piece of code:
- https://github.com/zama-ai/concrete/blob/ec8cb214fa10adaf9aaf436d85df834d84eb4d14/frontends/concrete-python/concrete/fhe/compilation/circuit.py#L77-L116

Hope it helps!

**Comment by RomanBredehoft** [comment]
To complement @umut-sahin's answer, Concrete-ML's currently works with Concrete v1 but we are planning on integrating v2 in our next release !

**Comment by maxwellgodv** [comment]
So this code does not simulate Homomorphic encryption？It uses Concrete v1 ？[cifar_brevitas_finetuning](https://github.com/zama-ai/concrete-ml/blob/release/1.1.x/use_case_examples/cifar_brevitas_finetuning/CifarInFhe.ipynb)

**Comment by RomanBredehoft** [comment]
Yes it does provide some kind of FHE simulation using Concrete v1's technique (graph evaluation + noise simulation), `fhe_simulation_inference` does not execute the inference in FHE ! The technique is just not as accurate as its second version (documentation: https://docs.zama.ai/concrete/tutorials/simulation), which will come with Concrete ML's next release. Still, you should currently be able to simulate FHE execution with a very good accuracy.

**Comment by RomanBredehoft** [comment]
Hello, if you are satisfied with the above answer, please feel free to close this issue 🙂

**Comment by maxwellgodv** [comment]
So is it to compile the quantitative model into an circuit, and then input the data into the circuit for prediction ？And, where can I find documents about circuit.
I don't have much knowledge about circuit.Thanks.

**Comment by umut-sahin** [comment]
There is no dedicated page for circuit, but there are pages for everything you can do with a circuit in https://docs.zama.ai/concrete!

Also, you can read the source code, every method is documented https://github.com/zama-ai/concrete/blob/main/frontends/concrete-python/concrete/fhe/compilation/circuit.py :slightly_smiling_face: 

And of course you can always ask directly to us, see https://www.zama.ai/community :wink:

**Comment by maxwellgodv** [comment]
OK,thanks
